import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playFair = Playfair_Display({
  variable: "--font-heading",
  subsets: ['latin']
})

const poppins = Poppins({
  weight: "400",
  variable: "--font-body",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${poppins.variable} ${playFair.className} ${geistMono.variable} `}>
        {children}

        <Script
  src="https://js.paystack.co/v1/inline.js"
  strategy="beforeInteractive"
/>
      </body>
    </html>
  );
}
